### ISSUE TITLE
client_publish/client_subscribe swapped in default config?

### ISSUE THREAD

**Issue by jorticus** [zebatus/sxvrs#2]
The HTTP server wasn't working for me, but I found out if I add the following to my config then the HTTP server starts working:
```
  client_publish  : sxvrs/daemon/{source_name}
  client_subscribe: sxvrs/clients/{source_name}
```

In config_reader.py I see it defaults to:
```
        self.mqtt_topic_client_publish = cnfg['mqtt'].get('client_publish', 'sxvrs/clients/{source_name}')
        self.mqtt_topic_client_subscribe = cnfg['mqtt'].get('client_subscribe', 'sxvrs/daemon/{source_name}')
```
I think the default mapping is incorrect? (HTTP is publishing to 'sxvrs/clients' instead of 'sxvrs/daemon')

**Comment by zebatus** [comment]
Hi,  Yes you are right. Thats definitely copy-paste typo there. Will fix it.
Many Thanks for the feedback.
